### ISSUE TITLE
tests fail

### ISSUE THREAD

**Issue by msimonc** [react-love/react-latest-framework#16]
Hi, Thanks for this (and English translations :)

I tried both Mac and Windows:

$ jest 
 FAIL  test/test.js
  ● async/await 函数测试

    TypeError: (0 , _fetchData.getData) is not a function
      
      at _callee$ (test/test.js:16:55)
      at tryCatch (node_modules/regenerator-runtime/runtime.js:65:40)
      at Generator.invoke [as _invoke] (node_modules/regenerator-runtime/runtime.js:303:22)
      at Generator.prototype.(anonymous function) [as next] (node_modules/regenerator-runtime/runtime.js:117:21)
      at step (test/test.js:8:333)
      at test/test.js:8:563
      at Object.<anonymous> (test/test.js:8:244)
      at process._tickCallback (internal/process/next_tick.js:109:7)

**Comment by hyy1115** [comment]
Because I modified the fetchData file function, it can not get getData, postData function in test

fetchData：

```javascript
import axios from 'axios';
const instance = axios.create({
    // baseURL: API_URL, //设置默认api路径
    timeout: 5000, //设置超时时间
    headers: {'X-Custom-Header': 'foobar'}
});

export default instance;
```
If you need to test, change test.js to：

```javascript
import instance from '../src/utils/fetchData';
test('async/await 函数测试', async () => {
    await expect(instance.get(`/api/book/list`)).resolve;
});

```

**Comment by msimonc** [comment]
Thanks!  In /build, can you code split and randomize the names of the js files for chunking and cache busting?  Nice project even if I can't read Chinese... :)
